# Chapter 1 Question answers

### Answer 1:

Import pandas & numpy

In [53]:
import pandas as pd

In [54]:
import numpy as np

pandas version

In [55]:
pd.__version__

'1.3.4'

In [56]:
df = pd.read_csv("housing.csv")

In [57]:
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY

### Answer 2:

In [58]:
print('Number of columns : ', df.shape[1])

Number of columns :  10


### Answer 3:

In [59]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Answer 4:

In [60]:
df.ocean_proximity.nunique()

5

### Answer 5:

In [61]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

### Answer 6:

In [62]:
df.total_bedrooms.mean()

537.8705525375618

In [63]:
df1 = df["total_bedrooms"].fillna(df.total_bedrooms.mean())

In [64]:
df1.mean()

537.8705525375639

### Answer 7:

In [65]:
df1 = df[
    df['ocean_proximity'] == 'ISLAND'
]
    

In [68]:
X = df1[['housing_median_age','total_rooms','total_bedrooms']]

In [69]:
X

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [70]:
XT = X.T

In [71]:
XT

8314    8315    8316   8317   8318
housing_median_age    27.0    52.0    52.0   52.0   29.0
total_rooms         1675.0  2359.0  2127.0  996.0  716.0
total_bedrooms       521.0   591.0   512.0  264.0  214.0

In [82]:
XTX = XT.dot(X)

In [83]:
XTX

housing_median_age  total_rooms  total_bedrooms
housing_median_age              9682.0     351053.0         91357.0
total_rooms                   351053.0   14399307.0       3772036.0
total_bedrooms                 91357.0    3772036.0        998358.0

In [84]:
XINV = np.linalg.inv(XTX)

In [85]:
XINV

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [86]:
y = np.array([950, 1300, 800, 1000, 1300])

In [87]:
y

array([ 950, 1300,  800, 1000, 1300])

In [89]:
xmult = XINV.dot(XT)

In [90]:
xmult.dot(y)

array([23.12330961, -1.48124183,  5.69922946])